services:
  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: meu_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'root'
      RABBITMQ_DEFAULT_PASS: 'root'
    ports:
      - '15672:15672'
      - '5672:5672'
      - '1000:1000'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq


volumes:
  rabbitmq_data:
  rabbitmq_log: